import { Inter } from "next/font/google";
//  import "./globals.css";

import Navbar from "@/components/servercomponents/Navbar"
import Footer from "@/components/servercomponents/Footer"
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
         <Navbar/>

        <div className="main">{children}</div>
        <Footer/>
      </body>
    </html>
    
  );
}
